"""Regression tests for the Time-LLM forecaster."""

import numpy as np
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.time_llm import TimeLLMForecaster
from sktime.tests.test_switch import run_test_for_class

# Reference forecasts were generated by calling the vendored Time-LLM Model
# (unofficial fork of KimMeen/Time-LLM, commit path sktime/libs/time_llm/TimeLLM.py)
# directly, bypassing TimeLLMForecaster. There is no installable upstream package
# and no public Time-LLM forecasting checkpoint; the wrapper constructs
# models/TimeLLM.py from config and a frozen LLM backbone.
#
# TINY_RANDOM is used instead of GPT2/BERT because those backends are not
# bitwise-stable on CPU in bfloat16 (SDPA kernel noise ~0.4-2.5 abs on airline).
# TINY_RANDOM still exercises patch embedding, prompt construction,
# reprogramming, and the projection head. GPT2/BERT loading paths remain
# covered by TimeLLMForecaster.get_test_params via VM estimator tests.
#
# The source Model.forecast casts patched inputs to bfloat16, so the model is
# converted with ``.to(torch.bfloat16)`` before eval, matching the wrapper.
#
#   from types import SimpleNamespace
#   import numpy as np, torch
#   from sktime.datasets import load_airline
#   from sktime.libs.time_llm.TimeLLM import Model
#
#   y_train = load_airline().iloc[:-12]
#   cfg = SimpleNamespace(
#       task_name="long_term_forecast",
#       pred_len=12,
#       seq_len=len(y_train),
#       llm_model="TINY_RANDOM",
#       llm_layers=1,
#       llm_dim=1,
#       patch_len=16,
#       stride=8,
#       d_model=8,
#       d_ff=1,
#       n_heads=1,
#       dropout=0.0,
#       enc_in=1,
#       prompt_domain=False,
#   )
#   torch.manual_seed(0)
#   model = Model(cfg).to("cpu").to(torch.bfloat16).eval()
#   x = torch.tensor(y_train.to_numpy().reshape(1, -1, 1), dtype=torch.float32)
#   with torch.no_grad():
#       preds = model.forward(x, None, None, None)
#   preds.detach().float().cpu().numpy().ravel()[:3]
#   # -> [287.0768127441406, 245.8953857421875, 251.5487518310547]
#
# The other cases only change task_name / llm_layers / patch_len / stride.
_TIME_LLM_REFERENCE_CASES = [
    pytest.param(
        {
            "task_name": "long_term_forecast",
            "llm_layers": 1,
            "patch_len": 16,
            "stride": 8,
        },
        [287.0768127441406, 245.8953857421875, 251.5487518310547],
        id="tiny-random-long-p16-s8",
    ),
    pytest.param(
        {
            "task_name": "long_term_forecast",
            "llm_layers": 1,
            "patch_len": 12,
            "stride": 6,
        },
        [262.99810791015625, 269.8055114746094, 245.79164123535156],
        id="tiny-random-long-p12-s6",
    ),
    pytest.param(
        {
            "task_name": "short_term_forecast",
            "llm_layers": 2,
            "patch_len": 16,
            "stride": 8,
        },
        [268.8719177246094, 270.0648498535156, 267.5234069824219],
        id="tiny-random-short-l2-p16-s8",
    ),
]


pytestmark = pytest.mark.skipif(
    not run_test_for_class(TimeLLMForecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)


@pytest.mark.parametrize(
    "forecaster_kwargs,expected_head",
    _TIME_LLM_REFERENCE_CASES,
)
def test_time_llm_airline_predictions_match_source_reference(
    forecaster_kwargs, expected_head
):
    """Time-LLM predictions match the vendored KimMeen/Time-LLM Model outputs."""
    import torch

    y = load_airline()
    y_train = y.iloc[:-12]
    fh = np.arange(1, 13)

    torch.manual_seed(0)
    forecaster = TimeLLMForecaster(
        pred_len=12,
        seq_len=len(y_train),
        llm_model="TINY_RANDOM",
        llm_dim=1,
        d_model=8,
        d_ff=1,
        n_heads=1,
        dropout=0.0,
        device="cpu",
        prompt_domain=False,
        **forecaster_kwargs,
    )
    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.to_numpy().ravel()[:3],
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
